#!/usr/bin/env python
# coding: utf-8

# In[1]:


#this code generates a semi-random dataset for the Microsoft Surface Ivey case, found here: https://www.iveycases.com/ProductView.aspx?id=99802
#the dataset was carefully curated to have particular features that support the facts of the case, aligning with potential strategic alternatives

#the structure of the dataset is three-years worth of data on enterprises who are Microsoft customers in the Asia-Pacific region
#each row includes some basic categorical data on the customer, along with revenue data for various lines of Microsoft's business attributed to that customer.


# In[2]:


import pandas as pd
from collections import OrderedDict
import numpy as np
import random


# In[3]:


#create 10k unique Microsoft customers

enterprise_id = []
i = 1
while i <= 10000:
    enterprise_id.append(i)
    i += 1;


# In[4]:


#create unique countries of HQ, sectors, and sizes for each company
#randomly generate a number between 0 and 1 to help assign these variables

#country_id_dict = {China:1,SK:2,India:3,Singapore:4,HK:5}

country_rand = []
sector_rand = []
size_rand = []

for x in enterprise_id:
    country_rand.append(random.random())

for x in enterprise_id:
    sector_rand.append(random.random())

for x in enterprise_id:
    size_rand.append(random.random())


# In[5]:


#assign countries to each Microsoft customer; 45% from China, 20% from South Korea, etc.

CNY_pcnt = .45
SK_pcnt = .65
IND_pcnt = .91
SGP_pcnt = 1

enterprise_country = []
for x in country_rand:
    if x <= CNY_pcnt:
        enterprise_country.append(1)
    elif x > CNY_pcnt and x <= SK_pcnt:
        enterprise_country.append(2)
    elif x > SK_pcnt and x <= IND_pcnt:
        enterprise_country.append(3)
    elif x > IND_pcnt and x <= SGP_pcnt:
        enterprise_country.append(4)

c = 0
sk = 0
ind = 0
sgp = 0
for x in enterprise_country:
    if x == 1:
        c += 1
    elif x ==2:
        sk += 1
    elif x == 3:
        ind += 1
    elif x == 4:
        sgp +=1

#test distribution of countries
print(c,sk,ind,sgp)


# In[6]:


#assign distribution of customer industries depending on country of origin
#x == 1 for Financial Services; x == 2 for Tech/Consulting; x == 3 for Healthcare; x == 4 for Education; x == 5 for Other


CNY_sectors = [.08,.4,.56,.82,1]
SK_sectors = [.16,.54,.72,.85,1]
IND_sectors = [.1,.45,.57,.81,1]
SGP_sectors = [.33,.48,.73,.8,1]

enterprise_sector = []
i = 0
for x in enterprise_country:
    if x == 1:
        y = CNY_sectors
        if sector_rand[i] <= y[0]:
            enterprise_sector.append(1);
        elif sector_rand[i] > y[0] and sector_rand[i] <= y[1]:
            enterprise_sector.append(2);
        elif sector_rand[i] > y[1] and sector_rand[i] <= y[2]:
            enterprise_sector.append(3);
        elif sector_rand[i] > y[2] and sector_rand[i] <= y[3]:
            enterprise_sector.append(4);
        elif sector_rand[i] > y[3] and sector_rand[i] <= y[4]:
            enterprise_sector.append(5);
    elif x == 2:
        y = SK_sectors
        if sector_rand[i] <= y[0]:
            enterprise_sector.append(1);
        elif sector_rand[i] > y[0] and sector_rand[i] <= y[1]:
            enterprise_sector.append(2);
        elif sector_rand[i] > y[1] and sector_rand[i] <= y[2]:
            enterprise_sector.append(3);
        elif sector_rand[i] > y[2] and sector_rand[i] <= y[3]:
            enterprise_sector.append(4);
        elif sector_rand[i] > y[3] and sector_rand[i] <= y[4]:
            enterprise_sector.append(5);
    elif x == 3:
        y = IND_sectors
        if sector_rand[i] <= y[0]:
            enterprise_sector.append(1);
        elif sector_rand[i] > y[0] and sector_rand[i] <= y[1]:
            enterprise_sector.append(2);
        elif sector_rand[i] > y[1] and sector_rand[i] <= y[2]:
            enterprise_sector.append(3);
        elif sector_rand[i] > y[2] and sector_rand[i] <= y[3]:
            enterprise_sector.append(4);
        elif sector_rand[i] > y[3] and sector_rand[i] <= y[4]:
            enterprise_sector.append(5);
    elif x == 4:
        y = SGP_sectors
        if sector_rand[i] <= y[0]:
            enterprise_sector.append(1);
        elif sector_rand[i] > y[0] and sector_rand[i] <= y[1]:
            enterprise_sector.append(2);
        elif sector_rand[i] > y[1] and sector_rand[i] <= y[2]:
            enterprise_sector.append(3);
        elif sector_rand[i] > y[2] and sector_rand[i] <= y[3]:
            enterprise_sector.append(4);
        elif sector_rand[i] > y[3] and sector_rand[i] <= y[4]:
            enterprise_sector.append(5);

    i += 1;


# In[7]:


#assign size for individual companies according to a distribution;
#size translates to estimated employee headcount

#size distribution was customized and conditionally dependent on country and sector, leading to complexities

CNY_size = [[.76,.925,.975,.995,1],[.66,.9,.96,.99,1],[.74,.92,.95,.985,1],[.91,.96,.98,.99,1],[.86,.95,.985,.995,1]]
SK_size = [[.79,.92,.98,.99,1],[.71,.92,.96,.98,1],[.81,.94,.97,.99,1],[.93,.97,.985,.995,1],[.88,.95,.97,.985,1]]
IND_size = [[.78,.93,.97,.99,1],[.69,.97,.99,.995,1],[.65,.86,.94,.98,1],[.93,.97,.985,.995,1],[.88,.95,.97,.985,1]]
SGP_size = [[.64,.85,.93,.993,1],[.8,.96,.98,.99,1],[.85,.96,.99,.995,1],[.89,.96,.985,.995,1],[.91,.97,.985,.995,1]]

enterprise_size = []
i = 0
for x in enterprise_country:
    if x == 1:
        y = CNY_size
        if enterprise_sector[i] == 1:
            if size_rand[i] <= y[0][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[0][0] and size_rand[i] <= y[0][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[0][1] and size_rand[i] <= y[0][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[0][2] and size_rand[i] <= y[0][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[0][3] and size_rand[i] <= y[0][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 2:
            if size_rand[i] <= y[1][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[1][0] and size_rand[i] <= y[1][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[1][1] and size_rand[i] <= y[1][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[1][2] and size_rand[i] <= y[1][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[1][3] and size_rand[i] <= y[1][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 3:
            if size_rand[i] <= y[2][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[2][0] and size_rand[i] <= y[2][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[2][1] and size_rand[i] <= y[2][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[2][2] and size_rand[i] <= y[2][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[2][3] and size_rand[i] <= y[2][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 4:
            if size_rand[i] <= y[3][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[3][0] and size_rand[i] <= y[3][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[3][1] and size_rand[i] <= y[3][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[3][2] and size_rand[i] <= y[3][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[3][3] and size_rand[i] <= y[3][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 5:
            if size_rand[i] <= y[4][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[4][0] and size_rand[i] <= y[4][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[4][1] and size_rand[i] <= y[4][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[4][2] and size_rand[i] <= y[4][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[4][3] and size_rand[i] <= y[4][4]:
                enterprise_size.append(5);

    elif x == 2:
        y = SK_size
        if enterprise_sector[i] == 1:
            if size_rand[i] <= y[0][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[0][0] and size_rand[i] <= y[0][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[0][1] and size_rand[i] <= y[0][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[0][2] and size_rand[i] <= y[0][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[0][3] and size_rand[i] <= y[0][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 2:
            if size_rand[i] <= y[1][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[1][0] and size_rand[i] <= y[1][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[1][1] and size_rand[i] <= y[1][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[1][2] and size_rand[i] <= y[1][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[1][3] and size_rand[i] <= y[1][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 3:
            if size_rand[i] <= y[2][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[2][0] and size_rand[i] <= y[2][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[2][1] and size_rand[i] <= y[2][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[2][2] and size_rand[i] <= y[2][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[2][3] and size_rand[i] <= y[2][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 4:
            if size_rand[i] <= y[3][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[3][0] and size_rand[i] <= y[3][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[3][1] and size_rand[i] <= y[3][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[3][2] and size_rand[i] <= y[3][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[3][3] and size_rand[i] <= y[3][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 5:
            if size_rand[i] <= y[4][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[4][0] and size_rand[i] <= y[4][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[4][1] and size_rand[i] <= y[4][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[4][2] and size_rand[i] <= y[4][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[4][3] and size_rand[i] <= y[4][4]:
                enterprise_size.append(5);

    elif x == 3:
        y = IND_size
        if enterprise_sector[i] == 1:
            if size_rand[i] <= y[0][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[0][0] and size_rand[i] <= y[0][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[0][1] and size_rand[i] <= y[0][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[0][2] and size_rand[i] <= y[0][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[0][3] and size_rand[i] <= y[0][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 2:
            if size_rand[i] <= y[1][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[1][0] and size_rand[i] <= y[1][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[1][1] and size_rand[i] <= y[1][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[1][2] and size_rand[i] <= y[1][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[1][3] and size_rand[i] <= y[1][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 3:
            if size_rand[i] <= y[2][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[2][0] and size_rand[i] <= y[2][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[2][1] and size_rand[i] <= y[2][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[2][2] and size_rand[i] <= y[2][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[2][3] and size_rand[i] <= y[2][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 4:
            if size_rand[i] <= y[3][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[3][0] and size_rand[i] <= y[3][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[3][1] and size_rand[i] <= y[3][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[3][2] and size_rand[i] <= y[3][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[3][3] and size_rand[i] <= y[3][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 5:
            if size_rand[i] <= y[4][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[4][0] and size_rand[i] <= y[4][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[4][1] and size_rand[i] <= y[4][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[4][2] and size_rand[i] <= y[4][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[4][3] and size_rand[i] <= y[4][4]:
                enterprise_size.append(5);

    elif x == 4:
        y = SGP_size
        if enterprise_sector[i] == 1:
            if size_rand[i] <= y[0][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[0][0] and size_rand[i] <= y[0][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[0][1] and size_rand[i] <= y[0][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[0][2] and size_rand[i] <= y[0][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[0][3] and size_rand[i] <= y[0][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 2:
            if size_rand[i] <= y[1][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[1][0] and size_rand[i] <= y[1][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[1][1] and size_rand[i] <= y[1][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[1][2] and size_rand[i] <= y[1][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[1][3] and size_rand[i] <= y[1][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 3:
            if size_rand[i] <= y[2][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[2][0] and size_rand[i] <= y[2][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[2][1] and size_rand[i] <= y[2][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[2][2] and size_rand[i] <= y[2][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[2][3] and size_rand[i] <= y[2][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 4:
            if size_rand[i] <= y[3][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[3][0] and size_rand[i] <= y[3][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[3][1] and size_rand[i] <= y[3][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[3][2] and size_rand[i] <= y[3][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[3][3] and size_rand[i] <= y[3][4]:
                enterprise_size.append(5);

        elif enterprise_sector[i] == 5:
            if size_rand[i] <= y[4][0]:
                enterprise_size.append(1);
            elif size_rand[i] > y[4][0] and size_rand[i] <= y[4][1]:
                enterprise_size.append(2);
            elif size_rand[i] > y[4][1] and size_rand[i] <= y[4][2]:
                enterprise_size.append(3);
            elif size_rand[i] > y[4][2] and size_rand[i] <= y[4][3]:
                enterprise_size.append(4);
            elif size_rand[i] > y[4][3] and size_rand[i] <= y[4][4]:
                enterprise_size.append(5);

    i += 1;


# In[8]:


#here the size variable is translated into workforce size

enterprise_workforce = []
for x in enterprise_size:
    if x == 1:
        enterprise_workforce.append(random.randrange(2,50,1))
    elif x == 2:
        enterprise_workforce.append(random.randrange(51,200,1))
    elif x == 3:
        enterprise_workforce.append(random.randrange(200,500,1))
    elif x == 4:
        enterprise_workforce.append(random.randrange(501,1000,1))
    elif x == 5:
        enterprise_workforce.append(random.randrange(1001,2500,1))


# In[9]:


### YEAR OVER YEAR CUSTOMER REVENUE DATA###
#first, start with the year 2015#

enterprise_revenue_id = []
enterprise_revenue_year_2015 = []
i = 1

while i < 10001:
    enterprise_revenue_id.append(i)
    i += 1

i = 2015
for x in enterprise_id:
    enterprise_revenue_year_2015.append(i)


# In[10]:


#now, add in the remaining data, starting with IT budget

enterprise_IT_budget_estimate_2015 = []

#need to incorporate rand that some will not be clients as of yet;
#in other words, account for the fact that some customers will be new in 2016 and 2017

for x,y,z,w in zip(enterprise_country, enterprise_sector, enterprise_size, enterprise_workforce):
    i = 0
    #CNY IT budget
    if x == 1:
        if y == 1:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(900,1100,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1200,1300,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1500,1700,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1600,2200,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2050,3000,1)*w)
        elif y == 2:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1300,1600,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1650,2200,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2300,2750,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2650,3350,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(3100,3550,1)*w)
        elif y == 3:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1100,1300,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1300,1450,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1375,1600,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1575,1775,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1700,3400,1)*w)
        elif y == 4:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1775,1900,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2000,2400,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2475,2700,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2850,3050,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(3000,3800,1)*w)
        elif y == 5:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1100,1300,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1300,1450,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1375,1600,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1575,1775,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1700,4000,1)*w)

    #SK IT budget
    elif x == 2:
        if y == 1:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1100,1350,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1300,1450,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1900,2050,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2050,2200,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2250,2900,1)*w)
        elif y == 2:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1300,1600,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1700,1900,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1850,2200,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2400,3000,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2800,3300,1)*w)
        elif y == 3:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1100,1300,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1300,1450,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1375,1600,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1575,1775,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1700,2400,1)*w)
        elif y == 4:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1400,1550,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1500,1700,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1675,1950,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2100,2450,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2800,3200,1)*w)
        elif y == 5:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1100,1300,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1300,1450,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1550,1700,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1750,1900,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1950,2700,1)*w)

 #IND budget
    elif x == 3:
        if y == 1:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(900,1100,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1200,1300,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1500,1700,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1600,2000,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2050,3000,1)*w)
        elif y == 2:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1300,2200,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1650,2600,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2300,2750,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2650,3150,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(3100,3300,1)*w)
        elif y == 3:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1500,1700,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1950,2350,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2500,2900,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2850,3300,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(3250,3500,1)*w)
        elif y == 4:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1450,1625,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1700,1850,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1900,2050,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1950,2400,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2450,2800,1)*w)
        elif y == 5:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1100,1300,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1300,1450,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1375,1600,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1575,2200,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1700,3200,1)*w)

    #HGK budget
    elif x == 4:
        if y == 1:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1750,2200,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2150,2450,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2500,2900,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2850,3300,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(3100,3800,1)*w)

        elif y == 2:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1100,1500,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1500,1700,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1850,2200,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2400,3000,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2800,3100,1)*w)
        elif y == 3:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1100,1300,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1300,1800,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1975,2800,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2400,3000,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2950,3500,1)*w)
        elif y == 4:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1400,1550,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1500,1700,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1675,1950,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2100,2450,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(2650,3100,1)*w)
        elif y == 5:
            if z == 1:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1100,1300,1)*w)
            elif z == 2:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1300,1450,1)*w)
            elif z == 3:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1550,1700,1)*w)
            elif z == 4:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1750,1900,1)*w)
            elif z == 5:
                enterprise_IT_budget_estimate_2015.append(random.randrange(1950,2700,1)*w)

    i += 1;




# In[11]:


#IT budget estimates beyond 2015 will either grow or shrink

enterprise_IT_budget_estimate_2016 = []
enterprise_IT_budget_estimate_2017 = []

for x in enterprise_IT_budget_estimate_2015:
    enterprise_IT_budget_estimate_2016.append(round(x*random.uniform(.95,1.15),0))
    enterprise_IT_budget_estimate_2017.append(round(x*random.uniform(.95,1.15),0))


# In[12]:


#establishing revenue data

enterprise_nonsurface_revenues_2016 = []
enterprise_surface_revenues_2016 = []
enterprise_other_revenues_2016 = []
enterprise_office_revenues_2016 = []
enterprise_cloud_revenues_2016 = []

enterprise_nonsurface_revenues_2017 = []
enterprise_surface_revenues_2017 = []
enterprise_other_revenues_2017 = []
enterprise_office_revenues_2017 = []
enterprise_cloud_revenues_2017 = []


# In[13]:


#Office 2015 revenues estimated on 12 month basis, multipled by the workforce size

office_revs_size_multiple = [12*10, 15*12, 17*12, 21*12, 24*12]

enterprise_office_revenues_2015 = []

for x,y in zip(enterprise_size, enterprise_workforce):
    enterprise_office_revenues_2015.append(y*office_revs_size_multiple[x-1])
    enterprise_office_revenues_2016.append(y*office_revs_size_multiple[x-1])
    enterprise_office_revenues_2017.append(y*office_revs_size_multiple[x-1])


# In[14]:


#Cloud 2015 revenues

#finance+healthcare grouped in first list by size, tech+edu+other in second

enterprise_cloud_revenues_2015 = []

for x,y,z in zip(enterprise_sector, enterprise_size, enterprise_IT_budget_estimate_2015):
    if x == 1 or x == 3:
        enterprise_cloud_revenues_2015.append(10/(random.randrange(25,40,1))*z)
        enterprise_cloud_revenues_2016.append(10/(random.randrange(25,40,1))*z)
        enterprise_cloud_revenues_2017.append(10/(random.randrange(25,40,1))*z)
    elif x == 2 or x == 4 or x == 5:
        enterprise_cloud_revenues_2015.append(10/(random.randrange(50,150,1))*z)
        enterprise_cloud_revenues_2016.append(10/(random.randrange(50,150,1))*z)
        enterprise_cloud_revenues_2017.append(10/(random.randrange(50,150,1))*z)


# In[15]:


#non-surface 2015 revenues

enterprise_nonsurface_revenues_2015 = []

for x,y,z in zip(enterprise_sector, enterprise_size, enterprise_IT_budget_estimate_2015):
    if x == 2 or x == 4:
        enterprise_nonsurface_revenues_2015.append(10/(random.randrange(30,60,1))*z)
        enterprise_nonsurface_revenues_2016.append(10/(random.randrange(30,60,1))*z)
        enterprise_nonsurface_revenues_2017.append(10/(random.randrange(30,60,1))*z)
    elif x == 1 or x == 3 or x == 5:
        enterprise_nonsurface_revenues_2015.append(10/(random.randrange(45,85,1))*z)
        enterprise_nonsurface_revenues_2016.append(10/(random.randrange(30,60,1))*z)
        enterprise_nonsurface_revenues_2017.append(10/(random.randrange(30,60,1))*z)


# In[16]:


#surface 2015 revenues

enterprise_surface_revenues_2015 = []

for x,y,z in zip(enterprise_sector, enterprise_size, enterprise_IT_budget_estimate_2015):
    if x == 2 or x == 4:
        enterprise_surface_revenues_2015.append(10/(random.randrange(100,200,1))*z)
        enterprise_surface_revenues_2016.append(10/(random.randrange(30,60,1))*z)
        enterprise_surface_revenues_2017.append(10/(random.randrange(30,60,1))*z)

    elif x == 1 or x == 3 or x == 5:
        enterprise_surface_revenues_2015.append(10/(random.randrange(125,300,1))*z)
        enterprise_surface_revenues_2016.append(10/(random.randrange(125,300,1))*z)
        enterprise_surface_revenues_2017.append(10/(random.randrange(125,300,1))*z)


# In[17]:


#other 2015 revenues

enterprise_other_revenues_2015 = []

for x,y,z in zip(enterprise_sector, enterprise_size, enterprise_IT_budget_estimate_2015):
    enterprise_other_revenues_2015.append(10/(random.randrange(100,350,1))*z)
    enterprise_other_revenues_2016.append(10/(random.randrange(100,350,1))*z)
    enterprise_other_revenues_2017.append(10/(random.randrange(100,350,1))*z)


# In[18]:


#now that I have everything, two items are left..
#first, create segments of "new" and "departing" customers (adoption rates in effect)
#then, generate revenue "growth" for select segments of customers

#1. desired segments --
## -- % of brand new customers each year (~5.5/%)
cust_2015_rand = []
for x in enterprise_id:
    cust_2015_rand.append(random.random())

cust_2015 = []

for x in cust_2015_rand:
    if x <= .8342893:
        cust_2015.append(1)
    else:
        cust_2015.append(0)


# In[19]:


#adjust non-customers in 2015 to not have data in that year

i = 0

for x in cust_2015:
    if x == 0:
        enterprise_nonsurface_revenues_2015[i] = 0
        enterprise_surface_revenues_2015[i] = 0
        enterprise_other_revenues_2015[i] = 0
        enterprise_office_revenues_2015[i] = 0
        enterprise_cloud_revenues_2015[i] = 0
        enterprise_IT_budget_estimate_2015[i] = 0
        i += 1;

    else:
        i += 1;



# In[20]:


#new customers in 2016/2017

cust_2016 = []
new_cust_2016 = []
cust_2017 = []
new_cust_2017 = []
cust_2016_rand = []

for x,y in zip(enterprise_id,cust_2015):
    if y == 0:
        cust_2016_rand.append(random.random())
    elif y == 1:
        cust_2016_rand.append(100)


for x in cust_2016_rand:
    if x <= .377596:
        cust_2016.append(1)
        cust_2017.append(1)
        new_cust_2016.append(1)
        new_cust_2017.append(0)

    elif x > .377596 and x <= 1:
        cust_2016.append(0)
        cust_2017.append(1)
        new_cust_2017.append(1)
        new_cust_2016.append(0)
    elif x == 100:
        cust_2016.append(1)
        cust_2017.append(1)
        new_cust_2016.append(0)
        new_cust_2017.append(0)



# In[21]:


#identify departing customers 2016,17
#build this from the ground up

departing_cust_2016 = []
departing_cust_2017 = []
departing_cust_rand = []

i = 0

for x in cust_2015:
    if x == 1:
        departing_cust_rand.append(random.random())
    elif x == 0:
        departing_cust_rand.append(random.randrange(2,101,1))


for x in departing_cust_rand:
    if x <= .050057:
        cust_2016[i] = 0
        cust_2017[i] = 0
    elif x > .050057 and x <= .090416:
        cust_2016[i] = 1
        cust_2017[i] = 0
    elif x > 98 and cust_2016[i] == 1 and cust_2017[i] == 1:
        cust_2017[i] = 0
    i += 1;


# In[22]:


#establish your dataframe

company_tuples = list(zip(enterprise_id,enterprise_sector,enterprise_country,enterprise_workforce, cust_2015, cust_2016, cust_2017, new_cust_2016, new_cust_2017, enterprise_IT_budget_estimate_2015, enterprise_nonsurface_revenues_2015, enterprise_office_revenues_2015))
company_tuples

company_description_df = pd.DataFrame(company_tuples, columns=['enterprise_id','enterprise_sector','enterprise_country','enterprise_workforce','cust_2015','cust_2016', 'cust_2017','n_c_2016','n_c_2017','IT_budget_2015', '2015 Nonsurface revs','2015 Office Revenues'])
#company_description_df

i = 0

for x,y,z in zip(cust_2015,cust_2016,cust_2017):
    if x == 0 and y == 1 and z == 0:
        i += 1


# In[23]:


enterprise_nonsurface_rand_2015 = []
enterprise_surface_rand_2015 = []
enterprise_other_rand_2015 = []
enterprise_office_rand_2015 = []
enterprise_cloud_rand_2015 = []

for x in cust_2015:
    if x == 1:
        enterprise_nonsurface_rand_2015.append(random.random())
        enterprise_surface_rand_2015.append(random.random())
        enterprise_other_rand_2015.append(random.random())
        enterprise_office_rand_2015.append(random.random())
        enterprise_cloud_rand_2015.append(random.random())
    elif x == 0:
        enterprise_nonsurface_rand_2015.append(100)
        enterprise_surface_rand_2015.append(100)
        enterprise_other_rand_2015.append(100)
        enterprise_office_rand_2015.append(100)
        enterprise_cloud_rand_2015.append(100)


# In[24]:


#finally, as mentioned earlier, adjust for non-existing customers in 2015

i = 0


for x,y,z,j,k,l,m,n in zip(enterprise_country,enterprise_sector,enterprise_size,
                           enterprise_nonsurface_rand_2015,enterprise_surface_rand_2015,
                           enterprise_other_rand_2015,enterprise_office_rand_2015,enterprise_cloud_rand_2015):
    if x == 1:
        if y == 1:
            if j > .67:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .1:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .3:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .12:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 2:
            if j > .85:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .3:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .08:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 3:
            if j > .65:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .1:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .08:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 4:
            if j > .8:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .25:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .92:
                enterprise_office_revenues_2015[i] = 0
            elif n > .06:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 5:
            if j > .7:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .15:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .08:
                enterprise_cloud_revenues_2015[i] = 0
    elif x == 2:
        if y == 1:
            if j > .8:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .07:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .7:
                enterprise_other_revenues_2015[i] = 0
            elif m > .98:
                enterprise_office_revenues_2015[i] = 0
            elif n > .12:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 2:
            if j > .73:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .12:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .96:
                enterprise_office_revenues_2015[i] = 0
            elif n > .11:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 3:
            if j > .65:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .10:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .32:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 4:
            if j > .82:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .14:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .98:
                enterprise_office_revenues_2015[i] = 0
            elif n > .09:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 5:
            if j > .7:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .13:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .13:
                enterprise_cloud_revenues_2015[i] = 0

    #RESUME HERE
    elif x == 3:
        if y == 1:
            if j > .77:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .18:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .8:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .12:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 2:
            if j > .83:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .08:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .08:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 3:
            if j > .7:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .11:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .15:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 4:
            if j > .72:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .45:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .92:
                enterprise_office_revenues_2015[i] = 0
            elif n > .06:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 5:
            if j > .7:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .3:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .08:
                enterprise_cloud_revenues_2015[i] = 0

    elif x == 4:
        if y == 1:
            if j > .7:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .09:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .7:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .75:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 2:
            if j > .75:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .08:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .35:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 3:
            if j > .55:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .11:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .75:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 4:
            if j > .68:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .12:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .92:
                enterprise_office_revenues_2015[i] = 0
            elif n > .4:
                enterprise_cloud_revenues_2015[i] = 0
        elif y == 5:
            if j > .7:
                enterprise_nonsurface_revenues_2015[i] = 0
            elif k > .3:
                enterprise_surface_revenues_2015[i] = 0
            elif l > .75:
                enterprise_other_revenues_2015[i] = 0
            elif m > .97:
                enterprise_office_revenues_2015[i] = 0
            elif n > .08:
                enterprise_cloud_revenues_2015[i] = 0

    i += 1;



# In[25]:


#non-customers in 2016

enterprise_nonsurface_rand_2016 = []
enterprise_surface_rand_2016 = []
enterprise_other_rand_2016 = []
enterprise_office_rand_2016 = []
enterprise_cloud_rand_2016 = []

for x in cust_2016:
    if x == 1:
        enterprise_nonsurface_rand_2016.append(random.random())
        enterprise_surface_rand_2016.append(random.random())
        enterprise_other_rand_2016.append(random.random())
        enterprise_office_rand_2016.append(random.random())
        enterprise_cloud_rand_2016.append(random.random())
    elif x == 0:
        enterprise_nonsurface_rand_2016.append(100)
        enterprise_surface_rand_2016.append(100)
        enterprise_other_rand_2016.append(100)
        enterprise_office_rand_2016.append(100)
        enterprise_cloud_rand_2016.append(100)


# In[26]:


#adjusted 2016/2017 revenues for growth or shrinkage

i = 0
for x,y,z,j,k,l,m,n,o,p in zip(enterprise_country,enterprise_sector,enterprise_size,
                                enterprise_nonsurface_rand_2016,
                                enterprise_surface_rand_2016,
                                enterprise_other_rand_2016,
                                enterprise_office_rand_2016,
                                enterprise_cloud_rand_2016, cust_2015, cust_2016):

    #growth for returning customers
    if o == 1 and p == 1:
        if x == 1:

            if y == 1:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.8,1.05))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.9,1.45))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.8,1.15 ))

            elif y == 2:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.80,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.90,1.85 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.75,1.3 ))

            elif y == 3:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.80,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.85,1.5 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.85,1.1 ))

            elif y == 4:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.80,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.85,1.7 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.75,1.35 ))

            elif y == 5:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.90,1.45 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.75,1.3 ))

        elif x == 2:
            if y == 1:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.95,1.1 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.85,1.15 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.12 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.7,1.05 ))

            elif y == 2:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.90,1.25 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.85,1.2 ))

            elif y == 3:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.85,1.15 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.95,1.65 ))

            elif y == 4:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.85,1.25 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.7,1.4 ))

            elif y == 5:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.90,1.15 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.75,1.25 ))

        elif x == 3:
            if y == 1:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.85,1.15 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.85,1.15 ))

            elif y == 2:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.90,1.85 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.8,1.35 ))

            elif y == 3:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.85,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.85,1.5 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.9,1.25 ))

            elif y == 4:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.85,1.75 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.8,1.4 ))

            elif y == 5:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.90,1.15 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.75,1.25 ))

        elif x == 4:
            if y == 1:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.95,1.1 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.85,1.15 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.12 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.95,1.35 ))

            elif y == 2:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.90,1.25 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.85,1.35 ))

            elif y == 3:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.85,1.15 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.95,1.4 ))

            elif y == 4:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.85,1.25 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.95,1.25 ))

            elif y == 5:
                enterprise_nonsurface_revenues_2016[i] = enterprise_nonsurface_revenues_2015[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2016[i] = enterprise_surface_revenues_2015[i]*(random.uniform(.90,1.15 ))
                enterprise_other_revenues_2016[i] = enterprise_other_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2016[i] = enterprise_office_revenues_2015[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2016[i] = enterprise_cloud_revenues_2015[i]*(random.uniform(.75,1.25 ))

    #numbers for new customers in 2016
    elif o == 0 and p == 1:
        if x == 1:
            if y == 1:
                if j > .67:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .14:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .8:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .12:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 2:
                if j > .65:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .35:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .05:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 3:
                if j > .65:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .14:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .08:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 4:
                if j > .7:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .24:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .92:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .06:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 5:
                if j > .7:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .3:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .08:
                    enterprise_cloud_revenues_2016[i] = 0
        elif x == 2:
            if y == 1:
                if j > .8:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .07:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .7:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .98:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .12:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 2:
                if j > .73:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .12:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .96:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .11:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 3:
                if j > .65:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .10:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .4:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 4:
                if j > .82:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .14:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .98:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .09:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 5:
                if j > .7:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .13:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .13:
                    enterprise_cloud_revenues_2016[i] = 0

        #RESUME HERE
        elif x == 3:
            if y == 1:
                if j > .77:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .2:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .8:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .12:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 2:
                if j > .72:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .24:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .3:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 3:
                if j > .7:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .11:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .35:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 4:
                if j > .68:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .28:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .92:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .25:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 5:
                if j > .7:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .3:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .08:
                    enterprise_cloud_revenues_2016[i] = 0

        elif x == 4:
            if y == 1:
                if j > .7:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .09:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .7:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .85:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 2:
                if j > .75:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .08:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .6:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 3:
                if j > .55:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .11:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .75:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 4:
                if j > .68:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .12:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .92:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .5:
                    enterprise_cloud_revenues_2016[i] = 0
            elif y == 5:
                if j > .7:
                    enterprise_nonsurface_revenues_2016[i] = 0
                elif k > .3:
                    enterprise_surface_revenues_2016[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2016[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2016[i] = 0
                elif n > .08:
                    enterprise_cloud_revenues_2016[i] = 0


    elif (o == 0 and p == 0) or (o == 1 and p == 0):
        enterprise_nonsurface_revenues_2016[i] = 0
        enterprise_surface_revenues_2016[i] = 0
        enterprise_other_revenues_2016[i] = 0
        enterprise_office_revenues_2016[i] = 0
        enterprise_cloud_revenues_2016[i] = 0
    i += 1;



# In[27]:


len(enterprise_IT_budget_estimate_2016)

i = 0

for x in cust_2016:
    if x == 0:
         enterprise_IT_budget_estimate_2016[i] = 0
    i += 1

i = 0
for x in cust_2017:
    if x == 0:
        enterprise_IT_budget_estimate_2017[i] = 0
    i += 1


# In[28]:


enterprise_nonsurface_rand_2017 = []
enterprise_surface_rand_2017 = []
enterprise_other_rand_2017 = []
enterprise_office_rand_2017 = []
enterprise_cloud_rand_2017 = []

for x in cust_2017:
    if x == 1:
        enterprise_nonsurface_rand_2017.append(random.random())
        enterprise_surface_rand_2017.append(random.random())
        enterprise_other_rand_2017.append(random.random())
        enterprise_office_rand_2017.append(random.random())
        enterprise_cloud_rand_2017.append(random.random())
    elif x == 0:
        enterprise_nonsurface_rand_2017.append(100)
        enterprise_surface_rand_2017.append(100)
        enterprise_other_rand_2017.append(100)
        enterprise_office_rand_2017.append(100)
        enterprise_cloud_rand_2017.append(100)


# In[29]:




i = 0
for x,y,z,j,k,l,m,n,o,p in zip(enterprise_country,enterprise_sector,enterprise_size,
                                enterprise_nonsurface_rand_2017,
                                enterprise_surface_rand_2017,
                                enterprise_other_rand_2017,
                                enterprise_office_rand_2017,
                                enterprise_cloud_rand_2017, cust_2016, cust_2017):

    #growth for returning customers
    if o == 1 and p == 1:
        if x == 1:

            if y == 1:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.95,1.05))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.85,1.4))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.85,1.15 ))

            elif y == 2:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.7,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.90,1.85 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.75,1.35 ))

            elif y == 3:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.85,1.4 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.85,1.35 ))

            elif y == 4:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.70,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.9,1.65 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.75,1.28 ))

            elif y == 5:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.90,1.4 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.75,1.25 ))

        elif x == 2:
            if y == 1:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.95,1.1 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.85,1.15 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.12 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.85,1.35 ))

            elif y == 2:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.90,1.25 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.85,1.2 ))

            elif y == 3:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.85,1.15 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.85,1.22 ))

            elif y == 4:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.85,1.25 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.95,1.25 ))

            elif y == 5:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.90,1.15 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.75,1.25 ))

        elif x == 3:
            if y == 1:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.85,1.4 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.85,1.15 ))

            elif y == 2:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.85,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.90,1.65 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.75,1.35 ))

            elif y == 3:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.85,1.15 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.85,1.25 ))

            elif y == 4:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.80,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.85,1.75 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.75,1.28 ))

            elif y == 5:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.90,1.15 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.75,1.25 ))

        elif x == 4:
            if y == 1:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.95,1.1 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.85,1.15 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.12 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.9,1.4 ))

            elif y == 2:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.90,1.25 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.85,1.35 ))

            elif y == 3:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.85,1.15 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.85,1.55 ))

            elif y == 4:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.85,1.25 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.95,1.25 ))

            elif y == 5:
                enterprise_nonsurface_revenues_2017[i] = enterprise_nonsurface_revenues_2016[i]*(random.uniform(.90,1.05 ))
                enterprise_surface_revenues_2017[i] = enterprise_surface_revenues_2016[i]*(random.uniform(.90,1.15 ))
                enterprise_other_revenues_2017[i] = enterprise_other_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_office_revenues_2017[i] = enterprise_office_revenues_2016[i]*(random.uniform(.95,1.05 ))
                enterprise_cloud_revenues_2017[i] = enterprise_cloud_revenues_2016[i]*(random.uniform(.75,1.25 ))

    #numbers for new customers in 2017
    elif o == 0 and p == 1:
        if x == 1:
            if y == 1:
                if j > .67:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .25:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .8:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .06:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 2:
                if j > .85:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .25:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .08:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 3:
                if j > .65:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .10:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .08:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 4:
                if j > .7:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .2:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .92:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .06:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 5:
                if j > .7:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .3:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .08:
                    enterprise_cloud_revenues_2017[i] = 0
        elif x == 2:
            if y == 1:
                if j > .8:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .07:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .7:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .98:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .12:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 2:
                if j > .73:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .12:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .96:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .11:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 3:
                if j > .65:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .10:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .16:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 4:
                if j > .82:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .14:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .98:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .09:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 5:
                if j > .7:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .13:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .13:
                    enterprise_cloud_revenues_2017[i] = 0

        #RESUME HERE
        elif x == 3:
            if y == 1:
                if j > .77:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .2:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .8:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .12:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 2:
                if j > .75:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .25:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .08:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 3:
                if j > .7:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .11:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .08:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 4:
                if j > .72:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .25:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .92:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .06:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 5:
                if j > .7:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .3:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .08:
                    enterprise_cloud_revenues_2017[i] = 0

        elif x == 4:
            if y == 1:
                if j > .7:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .09:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .7:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .85:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 2:
                if j > .75:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .08:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .4:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 3:
                if j > .55:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .11:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .85:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 4:
                if j > .68:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .12:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .92:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .45:
                    enterprise_cloud_revenues_2017[i] = 0
            elif y == 5:
                if j > .7:
                    enterprise_nonsurface_revenues_2017[i] = 0
                elif k > .3:
                    enterprise_surface_revenues_2017[i] = 0
                elif l > .75:
                    enterprise_other_revenues_2017[i] = 0
                elif m > .97:
                    enterprise_office_revenues_2017[i] = 0
                elif n > .08:
                    enterprise_cloud_revenues_2017[i] = 0


    elif (o == 0 and p == 0) or (o == 1 and p == 0):
        enterprise_nonsurface_revenues_2017[i] = 0
        enterprise_surface_revenues_2017[i] = 0
        enterprise_other_revenues_2017[i] = 0
        enterprise_office_revenues_2017[i] = 0
        enterprise_cloud_revenues_2017[i] = 0
    i += 1;


# In[30]:




df_year = []
i = 0
while i < 30000:
    if i < 10000:
        df_year.append(2015)

    elif i < 20000 and i >= 10000:
        df_year.append(2016)

    elif i < 30000 and i >= 20000:
        df_year.append(2017)
    i += 1


# In[31]:


#adjust categorical variables to appropriate names

i = 0
enterprise_country_hq = []
for x in enterprise_country:
    if x == 1:
        enterprise_country_hq.append('China')
    elif x  == 2:
        enterprise_country_hq.append('South Korea')
    elif x == 3:
        enterprise_country_hq.append('India')
    elif x == 4:
        enterprise_country_hq.append('Singapore')

i = 0
for x in enterprise_sector:
    if x == 1:
        enterprise_sector[i] = 'Financial Services'
    elif x == 2:
        enterprise_sector[i] = 'Technology and Consulting'
    elif x == 3:
        enterprise_sector[i] = 'Healthcare'
    elif x == 4:
        enterprise_sector[i] = 'Education'
    elif x == 5:
        enterprise_sector[i] = 'Other'
    i+=1


# In[32]:


#zip together in one large dataframe and export to csv; I actually forget which is the "good" copy it has been so long!

df_enterprise_id = enterprise_id*3
df_enterprise_sector = enterprise_sector*3
df_enterprise_country = enterprise_country_hq*3
df_enterprise_size = enterprise_size*3
df_enterprise_workforce = enterprise_workforce*3
df_enterprise_IT_budget_estimate = enterprise_IT_budget_estimate_2015+enterprise_IT_budget_estimate_2016+enterprise_IT_budget_estimate_2017
df_enterprise_cloud_revenues = enterprise_cloud_revenues_2015+enterprise_cloud_revenues_2016+enterprise_cloud_revenues_2017
df_enterprise_other_revenues = enterprise_other_revenues_2015+enterprise_other_revenues_2016+enterprise_other_revenues_2017
df_enterprise_nonsurface_revenues = enterprise_nonsurface_revenues_2015+enterprise_nonsurface_revenues_2016+enterprise_nonsurface_revenues_2017
df_enterprise_surface_revenues = enterprise_surface_revenues_2015+enterprise_surface_revenues_2016+enterprise_surface_revenues_2017
df_enterprise_office_revenues = enterprise_office_revenues_2015+enterprise_office_revenues_2016+enterprise_office_revenues_2017

big_df = list(zip(df_enterprise_id,df_enterprise_sector,df_enterprise_country,df_enterprise_size,df_enterprise_workforce, df_year,
                 df_enterprise_IT_budget_estimate,df_enterprise_cloud_revenues,df_enterprise_other_revenues,
                 df_enterprise_nonsurface_revenues,df_enterprise_surface_revenues,df_enterprise_office_revenues))

big_df = pd.DataFrame(big_df, columns = ['enterprise_id','Sector', 'Enterprise Country Headquarters','enterprise_size', 'Workforce Size', 'Year',
                                        'Enterprise IT Budget Estimate','Cloud Service Revenues',
                                        'Other Service Revenues','Non-Surface Product Revenues',
                                        'Surface Product Revenues','Office Products Revenues'])
big_df.to_csv (r'C:\Users\Mac\Desktop\Ivey\MIFTC\Case Competition\Final Data Copies\company_description_df_final940pm.csv', index = None, header=True)


# In[33]:


#zip together in one large dataframe and export to csv; I actually forget which is the "good" copy it has been so long!

company_tuples = list(zip(enterprise_id,enterprise_sector, enterprise_country_hq,enterprise_size, enterprise_workforce,cust_2015, cust_2016, cust_2017, enterprise_IT_budget_estimate_2015, enterprise_IT_budget_estimate_2016, enterprise_IT_budget_estimate_2017, enterprise_nonsurface_revenues_2015, enterprise_nonsurface_revenues_2016, enterprise_nonsurface_revenues_2017, enterprise_office_revenues_2015,enterprise_office_revenues_2016,enterprise_office_revenues_2017, enterprise_surface_revenues_2015, enterprise_surface_revenues_2016, enterprise_surface_revenues_2017, enterprise_other_revenues_2015,enterprise_other_revenues_2016,enterprise_other_revenues_2017,enterprise_cloud_revenues_2015,enterprise_cloud_revenues_2016,enterprise_cloud_revenues_2017))
company_tuples

company_description_df = pd.DataFrame(company_tuples, columns = ['enterprise_id','enterprise_sector', 'enterprise_country','enterprise_size', 'Workforce Size','cust_2015', 'cust_2016', 'cust_2017', 'enterprise_IT_budget_estimate_2015', 'enterprise_IT_budget_estimate_2016', 'enterprise_IT_budget_estimate_2017', 'enterprise_nonsurface_revenues_2015', 'enterprise_nonsurface_revenues_2016', 'enterprise_nonsurface_revenues_2017', 'enterprise_office_revenues_2015', 'enterprise_office_revenues_2016','enterprise_office_revenues_2017', 'enterprise_surface_revenues_2015', 'enterprise_surface_revenues_2016', 'enterprise_surface_revenues_2017', 'enterprise_other_revenues_2015','enterprise_other_revenues_2016','enterprise_other_revenues_2017','enterprise_cloud_revenues_2015','enterprise_cloud_revenues_2016','enterprise_cloud_revenues_2017'])
company_description_df
company_description_df.to_csv (r'C:\Users\Mac\Desktop\Ivey\MIFTC\Case Competition\Final Data Copies\company_description_df_finalv4.csv', index = None, header=True)


# In[34]:


#brand new customers defined...
#need to do a few more things:
#first, segment customers by growth (sector+country+size+new) and add in 2016/2017 #s;
#AND segment customers by product (low but growing % of surface product, for example)
#eliminate the 2016 #s of new 2017 customers
#add in departing customers for 2016/2017
#round numbers
#eliminate sub $500 revenues for product
#OPTIONAL: add in trend for departing customers
#OPTIONAL: new customers never depart. may want to add that in
